### probar microservicio
GET http://127.0.0.1:8001/

### ruta de prueba de usuarios
GET http://127.0.0.1:8001/usuarios/prueba


###############################################################
#   CRUD COMPLETO DE USUARIOS (TABLA users)
###############################################################

### crear usuario
POST http://127.0.0.1:8001/usuarios
Content-Type: application/json

{
  "name": "juan",
  "email": "juan@gmail.com",
  "password": "123456",
  "role": "gestor",
  "token": ""
}

### listar usuarios
GET http://127.0.0.1:8001/usuarios

### obtener un usuario por id
GET http://127.0.0.1:8001/usuarios/1

### actualizar usuario
PUT http://127.0.0.1:8001/usuarios/1
Content-Type: application/json

{
  "name": "juan perez",
  "email": "nuevo@gmail.com",
  "password": "nueva123",
  "role": "administrador",
  "token": ""
}

### eliminar usuario
DELETE http://127.0.0.1:8001/usuarios/1
