#############################################
#            MICRO SERVICIO VUELOS          #
#        TESTS COMPLETOS - .HTTP FILE       #
#############################################

#############################################
#                 NAVES                    #
#############################################

### Obtener todas las naves
GET http://127.0.0.1:9000/naves/all
Accept: application/json

###

### Crear nave
POST http://127.0.0.1:9000/naves/create
Content-Type: application/json

{
  "nombre": "Nave Estelar",
  "capacidad": 180,
  "tipo": "Comercial"
}

###

### Actualizar nave (id=1)
PUT http://127.0.0.1:9000/naves/update/1
Content-Type: application/json

{
  "nombre": "Nave Estelar Pro",
  "capacidad": 250,
  "tipo": "VIP"
}

###

### Eliminar nave (id=1)
DELETE http://127.0.0.1:9000/naves/delete/1


#############################################
#                 VUELOS                    #
#############################################

### Obtener todos los vuelos
GET http://127.0.0.1:9000/vuelos/all
Accept: application/json

###

### Crear vuelo
POST http://127.0.0.1:9000/vuelos/create
Content-Type: application/json

{
  "origen": "Bogotá",
  "destino": "Medellín",
  "fecha": "2025-12-01",
  "hora": "08:30",
  "precio": 350000,
  "nave_id": 2
}

###

### Actualizar vuelo
PUT http://127.0.0.1:9000/vuelos/update/1
Content-Type: application/json

{
  "precio": 400000,
  "destino": "Cali"
}

###

### Eliminar vuelo
DELETE http://127.0.0.1:9000/vuelos/delete/1

###

### Buscar vuelos
GET http://127.0.0.1:9000/vuelos/search?origen=Bogotá&destino=Medellín&fecha=2025-12-01
Accept: application/json


#############################################
#                RESERVAS                   #
#############################################
# NOTA: ESTAS RUTAS REQUIEREN TOKEN         #
#############################################

### Obtener token del gestor (Microservicio Usuarios)
POST http://127.0.0.1:8000/usuarios/login
Content-Type: application/json

{
  "email": "gestor@gmail.com",
  "password": "1234"
}

###
# COPIA EL TOKEN MANUALMENTE Y PÉGALO ABAJO
###

### Crear reserva (requiere token)
POST http://127.0.0.1:9000/reservas/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "vuelo_id": 2
}

###

### Ver mis reservas (requiere token)
GET http://127.0.0.1:9000/reservas/my
Authorization: Bearer {{token}}
Accept: application/json

###

### Cancelar reserva (requiere token)
DELETE http://127.0.0.1:9000/reservas/delete/1
Authorization: Bearer {{token}}
