#############################################
#            MICRO SERVICIO VUELOS          #
#        TESTS COMPLETOS - .HTTP FILE       #
#############################################
@token = e818da10d1f65e2d4ed9d3dd4495a1ece0677a654d5cd5cc4dc7756923d7d4de

#############################################
#                 NAVES                     #
#############################################

### Obtener todas las naves
GET http://127.0.0.1:9000/naves/all
Accept: application/json

###

### Crear nave
POST http://127.0.0.1:9000/naves/create
Content-Type: application/json

{
  "name": "Aeronave X1",
  "capacity": 180,
  "model": "Airbus A320"
}

###

### Actualizar nave (id=1)
PUT http://127.0.0.1:9000/naves/update/1
Content-Type: application/json

{
  "name": "Aeronave X1 Pro",
  "capacity": 250,
  "model": "Airbus A321"
}

###

### Eliminar nave (id=1)
DELETE http://127.0.0.1:9000/naves/delete/1


#############################################
#                 VUELOS                    #
#############################################

### Obtener todos los vuelos
GET http://127.0.0.1:9000/vuelos/all
Accept: application/json

###

### Crear vuelo
POST http://127.0.0.1:9000/vuelos/create
Content-Type: application/json

{
  "origin": "Bogotá",
  "destination": "Medellín",
  "departure": "2025-12-01 08:00",
  "arrival": "2025-12-01 09:00",
  "price": 350000,
  "nave_id": 2
}

###

### Actualizar vuelo (id=1)
PUT http://127.0.0.1:9000/vuelos/update/1
Content-Type: application/json

{
  "price": 400000,
  "destination": "Cali"
}

###

### Eliminar vuelo (id=1)
DELETE http://127.0.0.1:9000/vuelos/delete/1

###

### Buscar vuelos
GET http://127.0.0.1:9000/vuelos/search?origin=Bogotá&destination=Medellín&departure=2025-12-01
Accept: application/json


#############################################
#                RESERVAS                   #
#############################################
# NOTA: ESTAS RUTAS REQUIEREN TOKEN         #
#############################################

# TOKEN (lo pegas aquí abajo si quieres reutilizarlo)
# Token directo:
# e818da10d1f65e2d4ed9d3dd4495a1ece0677a654d5cd5cc4dc7756923d7d4de

### Crear reserva
POST http://127.0.0.1:9000/reservas/create
Authorization: Bearer e818da10d1f65e2d4ed9d3dd4495a1ece0677a654d5cd5cc4dc7756923d7d4de
Content-Type: application/json

{
  "flight_id": 2
}

###

### Ver mis reservas
GET http://127.0.0.1:9000/reservas/my
Authorization: Bearer e818da10d1f65e2d4ed9d3dd4495a1ece0677a654d5cd5cc4dc7756923d7d4de
Accept: application/json

###

### Cancelar reserva (id=1)
DELETE http://127.0.0.1:9000/reservas/delete/1
Authorization: Bearer e818da10d1f65e2d4ed9d3dd4495a1ece0677a654d5cd5cc4dc7756923d7d4de
